### ISSUE TITLE
Hupe just once or configurable

### ISSUE THREAD

**Issue by nh-finescale** [nh-finescale/ln2block#10]
The message for LNCV_ADR_HUPE is sent three times. For a buzzer this fits, for a soundplayer only once is enough. Either configurable or only once suffices

**Comment by Bahn-Papa** [comment]
This is already implemented.
Look for config bit "ANRUECKMELDER_FROM _LN2BLOCK".
If this bit is set then the box will control the "Hupe".
If this bit is cleared then there will be only 1 message to flag "please hup now".

**Comment by nh-finescale** [comment]
I will Test

**Comment by nh-finescale** [comment]
updated in wiki
