### ISSUE TITLE
Need to send EINFAHR_KONTAKT again to leave state 1._ACHSE

### ISSUE THREAD

**Issue by Kleinbahner** [nh-finescale/ln2block#19]
When receiving a train, the message EINFAHR_KONTAKT has to be send in order to change the state to 1._ACHSE. Then a second message EINFAHR_KONTAKT has to be send in order to go to state GERAEUMT. This might be difficult when using a current sensor that is longer then the loco. There, only one message will be generated.
Could this be changed to automatically forward to the next state or to react on a inverted EINFAHR_KONTAKT message (contact released)?

**Comment by nh-finescale** [comment]
issue is related to new config bits for 3 timers, which is separate issue. This one can be closed
