### ISSUE TITLE
Swap OLED Orientation

### ISSUE THREAD

**Issue by nh-finescale** [nh-finescale/ln2block#2]
The OLED display is dependent on the orientation of board in the Stellwerk (if the OLED is mounted fixed on the board). To be able to read the OLED if mounted upside down, a configuration could be implemented this flips the OLED display upside down

**Comment by Bahn-Papa** [comment]
Add a configuration bit 'DISPLAY_FLIP' that controls the orientation of the OLED display. If the bit is set the displayed text will be flipped (rotated by 180 degree).
