### ISSUE TITLE
LNCV programming does not work with >1 device

### ISSUE THREAD

**Issue by nh-finescale** [nh-finescale/ln2block#27]
When >1 device is on loconet, ln2block does not react to direct address or broadcast messages.
ln2b v2.08/5
1 ln2b + 1 other device > no reaction
2 ln2b (different lncv[0] ) > no reaction
1 ln2b = reaction
both for broadcast (65535) and lncv[0] addressing

expected behaviour: ln2b reacts when article number (15100) and lncv[0] are correct or with broadcast and correct article number

**Comment by Bahn-Papa** [comment]
Ralf and I tested this on Thursday evening (16.12.2021). We had no problems with broadcast messages and also no problems with more than one device on the loconet.
We can communicat with each single device on the loconet.
