### ISSUE TITLE
Richtungsbetrieb not working

### ISSUE THREAD

**Issue by nh-finescale** [nh-finescale/ln2block#29]
Setting bit #2 in LNCV2 does not create a working block connection. Erlaubnis, End Feld and Anf Feld remain empty in OLED. Train can be sent, but is not picked up by ln2b in Richtungsbetrieb mode.
Tested with peers:
- ln2b v2.08/5 on other side (with Erlaubnis erhalten shown)
- Blockplatine with Relaisblock 1-GL (arrow shows Erlaubnis)
Both situations not working. Picture shows LN2b <->LN2b setup
![IMG_5328](https://user-images.githubusercontent.com/77726489/145888421-443a2e78-34ae-4045-9dbc-c67b6c450a65.jpg)

**Comment by Bahn-Papa** [comment]
This bug is fixed and tested.
Richtungsbetrieb works as expected now.
