### ISSUE TITLE
Handle Vorblock manually in Felderblock

### ISSUE THREAD

**Issue by nh-finescale** [nh-finescale/ln2block#3]
A Vorblock should be handled manually in Felderblock, not automatically as in Tf71 and Relaisblock. Add a configuration switch to set Felderblock type and handle logic accordingly. Add Vorblock input Additionally?

**Comment by nh-finescale** [comment]
need to test

**Comment by nh-finescale** [comment]
No Vorblock possible if LNCV2 bit 4 set. Exit signal is not recognized, vorblock cannot be sent to other side

**Comment by Bahn-Papa** [comment]
This bug is fixed and tested.
Felderblock is working as expected now.
